[package]
name = "axi-uart16550"
version = "0.1.0"
description = "AXI UART16550 IP core driver"
author = ["Robin Mueller <muellerr@irs.uni-stuttgart.de>"]
rust-version = "1.85.1"
edition = "2024"
homepage = "https://egit.irs.uni-stuttgart.de/rust/axi-uart16550"
repository = "https://egit.irs.uni-stuttgart.de/rust/axi-uart16550"
license = "MIT OR Apache-2.0"

[dependencies]
derive-mmio = "0.6"
bitbybit = "1.4"
arbitrary-int = "2"
nb = "1"
libm = "0.2"
critical-section = "1"
thiserror = { version = "2", default-features = false }
fugit = "0.3"
embedded-hal-async = "1"
embedded-hal-nb = "1"
embedded-io = "0.7"
embedded-io-async = "0.7"
embassy-sync = "0.7"
raw-slicee = "0.1"

[features]
default = ["1-waker"]
1-waker = []
2-wakers = []
4-wakers = []
8-wakers = []
16-wakers = []
32-wakers = []

[dev-dependencies]
approx = "0.5"
